"""Inicializar migraciones

Revision ID: 5dd1b46cdbcf
Revises: 
Create Date: 2025-06-15 00:16:23.623570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd1b46cdbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('destacado', sa.Boolean(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('anime',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('anime',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('destacado')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
